# Generated by Django 3.0.3 on 2020-08-29 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studymaterial', '0006_auto_20200826_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(blank=True, max_length=150, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studymaterial.ClassRoom')),
            ],
        ),
    ]
