# Generated by Django 3.0.3 on 2020-08-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignmentsubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True)),
                ('submitted_asignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment.AssignmentSubmit')),
            ],
        ),
    ]
