# Generated by Django 3.0.3 on 2020-09-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignmentgrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentpdf',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
