# Generated by Django 3.0.3 on 2020-09-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignmentpdf_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentpdf',
            name='due_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
