# Generated by Django 3.0.3 on 2020-09-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20200901_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentgrades',
            name='score',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
