# Generated by Django 3.0.3 on 2020-08-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymaterial', '0003_auto_20200812_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='video_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
