# Generated by Django 3.1 on 2020-08-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymaterial', '0008_auto_20200826_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='choice', to='studymaterial.Choice'),
        ),
    ]
